### ISSUE TITLE
Null names

### ISSUE THREAD

**Issue by ilyankou** [drei01/geojson-world-cities#1]
Hi @drei01,

Thank you for this wonderful resource. @amensiko and I were having troubles making a choropleth with `folium`, and after some troubleshooting we realized that was because 2 thousand cities had NAME values set to null. We cleaned up the file, would you be interested in adding it alongside with the original? (I can send a pull request & add a note in README). It's totally ok if not.

Thanks!

**Comment by drei01** [comment]
Hey, 

I'm glad the data is useful for you :). I'd be very happy to include your cleaned up version of the data. You can create a pull request (to replace the file rather than add a new one) and I'll take a look.

Matt

**Comment by ilyankou** [comment]
Hey @drei01, let me know if the pull request #2 looks good. I managed to reduce the file size by about 10Mb by limiting precision to 5 decimal points (that's about 1 meter in the real world), which is more than enough given the city boundaries are approximate for most places I looked at.

**Comment by drei01** [comment]
Looks good to me. I ran https://github.com/mapbox/geojsonhint on it and there are no new errors. Thank you for your contribution :)
